### ISSUE TITLE
FK Constraint issue (again)

### ISSUE THREAD

**Issue by bdgeorge** [jreinke/magento-stock-movements#10]
I'm seeing a similar problem to issue #8 

```
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child     row: a foreign key constraint fails (`store_db`.`bubble_stock_movement`, CONSTRAINT `FK_STOCK_MOVEMENT_USER` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE)
```

However I'm using version 1.2.

It happens at some point during the checkout, the error message comes through in a "Payment Transaction Failed Email".

It doesn't actually stop the order processing, but it does stop the stock movement from logging.

It appears that despite the fix for issue #8 being in place the constraint still exists in the DB schema, it's as if the upgrade-1.0.0-1.1.0.php ran but failed to drop the FK - it's still visible in the schema. I know the script ran because I can see the is_admin TINYINT has been added to the movements table.

Checking the logs the stack dump is as follows:

```
013-11-18T21:09:58+00:00 ERR (3):
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`store_db`.`bubble_stock_movement`, CONSTRAINT `FK_STOCK_MOVEMENT_USER` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE)' in /home/store/public_html/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /home/store/public_html/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /home/store/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /home/store/public_html/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /home/store/public_html/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#4 /home/store/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `bu...', Array)
#5 /home/store/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(389): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `bu...', Array)
#6 /home/store/public_html/lib/Zend/Db/Adapter/Abstract.php(574): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `bu...', Array)
#7 /home/store/public_html/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(448): Zend_Db_Adapter_Abstract->insert('bubble_stock_mo...', Array)
#8 /home/store/public_html/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Core_Model_Resource_Db_Abstract->save(Object(Bubble_StockMovements_Model_Stock_Movement))
#9 /home/store/public_html/app/code/community/Bubble/StockMovements/Model/Stock/Observer.php(134): Mage_Core_Model_Abstract->save()
#10 /home/store/public_html/app/code/community/Bubble/StockMovements/Model/Stock/Observer.php(119): Bubble_StockMovements_Model_Stock_Observer->insertStockMovement(Object(Mage_CatalogInventory_Model_Stock_Item), 'Product ordered...')
#11 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(1303): Bubble_StockMovements_Model_Stock_Observer->checkoutAllSubmitAfter(Object(Varien_Event_Observer))
#12 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(1284): Mage_Core_Model_App->_callObserverMethod(Object(Bubble_StockMovements_Model_Stock_Observer), 'checkoutAllSubm...', Object(Varien_Event_Observer))
#13 /home/store/public_html/app/Mage.php(416): Mage_Core_Model_App->dispatchEvent('checkout_submit...', Array)
#14 /home/store/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(828): Mage::dispatchEvent('checkout_submit...', Array)
#15 /home/store/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(501): Mage_Checkout_Model_Type_Onepage->saveOrder()
#16 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(420): Mage_Checkout_OnepageController->saveOrderAction()
#17 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#18 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(349): Mage_Core_Controller_Varien_Front->dispatch()
#20 /home/store/public_html/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#21 /home/store/public_html/index.php(84): Mage::run('', 'store')
#22 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`store_db`.`bubble_stock_movement`, CONSTRAINT `FK_STOCK_MOVEMENT_USER` FOREIGN KEY (`user_id`) REFERENCES `admin_user` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE)' in /home/store/public_html/lib/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /home/store/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/store/public_html/lib/Zend/Db/Statement.php(300): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/store/public_html/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /home/store/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `bu...', Array)
#4 /home/store/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(389): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `bu...', Array)
#5 /home/store/public_html/lib/Zend/Db/Adapter/Abstract.php(574): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `bu...', Array)
#6 /home/store/public_html/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(448): Zend_Db_Adapter_Abstract->insert('bubble_stock_mo...', Array)
#7 /home/store/public_html/app/code/core/Mage/Core/Model/Abstract.php(318): Mage_Core_Model_Resource_Db_Abstract->save(Object(Bubble_StockMovements_Model_Stock_Movement))
#8 /home/store/public_html/app/code/community/Bubble/StockMovements/Model/Stock/Observer.php(134): Mage_Core_Model_Abstract->save()
#9 /home/store/public_html/app/code/community/Bubble/StockMovements/Model/Stock/Observer.php(119): Bubble_StockMovements_Model_Stock_Observer->insertStockMovement(Object(Mage_CatalogInventory_Model_Stock_Item), 'Product ordered...')
#10 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(1303): Bubble_StockMovements_Model_Stock_Observer->checkoutAllSubmitAfter(Object(Varien_Event_Observer))
#11 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(1284): Mage_Core_Model_App->_callObserverMethod(Object(Bubble_StockMovements_Model_Stock_Observer), 'checkoutAllSubm...', Object(Varien_Event_Observer))
#12 /home/store/public_html/app/Mage.php(416): Mage_Core_Model_App->dispatchEvent('checkout_submit...', Array)
#13 /home/store/public_html/app/code/core/Mage/Checkout/Model/Type/Onepage.php(828): Mage::dispatchEvent('checkout_submit...', Array)
#14 /home/store/public_html/app/code/core/Mage/Checkout/controllers/OnepageController.php(501): Mage_Checkout_Model_Type_Onepage->saveOrder()
#15 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Action.php(420): Mage_Checkout_OnepageController->saveOrderAction()
#16 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('saveOrder')
#17 /home/store/public_html/app/code/core/Mage/Core/Controller/Varien/Front.php(176): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#18 /home/store/public_html/app/code/core/Mage/Core/Model/App.php(349): Mage_Core_Controller_Varien_Front->dispatch()
#19 /home/store/public_html/app/Mage.php(640): Mage_Core_Model_App->run(Array)
#20 /home/store/public_html/index.php(84): Mage::run('', 'store')
#21 {main}
```

**Comment by Imrozanjum** [comment]
Hi I am getting when add/update product after add this.

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`databasename`.`bubble_stock_movement`, CONSTRAINT `FK_STOCK_MOVEMENT_ITEM` FOREIGN KEY (`item_id`) REFERENCES `cataloginventory_stock_item` (`item_id`) ON DELETE CASCADE ON UPDATE CASCADE), query was: INSERT INTO `bubble_stock_movement` (`item_id`, `user`, `user_id`, `is_admin`, `qty`, `is_in_stock`, `message`, `created_at`) VALUES (?, ?, ?, ?, ?, ?, ?, '2019-07-12 11:37:54')

Please suggest me.
